version: '3.8'

services:
  web:
    image: nginx:alpine
    restart: always
    ports:
      - 8099:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./:/var/www
    networks:
      - example-network
    

  php:
    image: php:7.4-fpm
    restart: always
    volumes:
      - ./:/var/www
    networks:
      - example-network

  mysql:
       image: mysql:5.7.22
       restart: unless-stopped
       environment:
           MYSQL_DATABASE: dbdata
           MYSQL_ROOT_PASSWORD: root
           MYSQL_PASSWORD: root
           MYSQL_USER: user_mysql
       volumes:
           - ./.docker/mysql/dbdata:/var/lib/mysql
       ports:
           - 3388:3306
       networks:
           - example-network

networks:
  example-network:
    driver: bridge
